### PR TITLE
Add ability to run as a Windows service

### LINKED ISSUE #30: Run as a Windows service
It would be great to have ability to run sql_exporter as a Windows service. Now I register service with sc.exe, but it crush with error 7000:
> The sql_exporter service failed to start due to the following error: 
> The service did not respond to the start or control request in a timely fashion.

### PR DESCRIPTION
**Pull request by kworr**
Fixes #30 .

### CODE REVIEW

**Comment by burningalchemist** [comment]
Hi @kworr!
Why did you close the PR? It doesn't work or something else?

**Comment by kworr** [comment]
> Hi @kworr!
> Why did you close the PR? It doesn't work or something else?

I'm not good at Go and it's not working for me.

**Comment by burningalchemist** [comment]
@kworr Could you explain what was your experience with that package or what was the expected result and what exactly didn't work? It would be helpful in order to get this feature delivered. :)

**Comment by kworr** [comment]
I think my first attempt was pretty fine, though it looks like I need to commit whole related package to the repo. I'm not sure whether this is right or I should use something to prepare all prerequisites...

By that time I already found out that sql_exporter is mangling MySQL time intervals and switched to query_exporter.

**Comment by burningalchemist** [comment]
@kworr Oh, ok, got it. Thanks!

And if you have some time, could you please also explain the issue with MySQL time intervals? It might become an issue ticket, by the way. :)

**Pull request closed without merging**
